"""
Stripe Balance Transaction integration.

Provides access to the financial movement generated by
Stripe charges, including gross amount, processing fees,
and net amount.
"""

from integrations.stripe.clients import StripeClient


class StripeBalanceTransactions:
    """
    Access Stripe balance transactions.
    """

    def __init__(
        self,
        client: StripeClient,
    ) -> None:
        self.client = client

    def retrieve(
        self,
        balance_transaction_id: str,
    ):
        """
        Retrieve a Stripe balance transaction.
        """

        return self.client.stripe.BalanceTransaction.retrieve(
            balance_transaction_id
        )